#!/usr/bin/env php
<?php

require __DIR__.'/../../../vendor/autoload.php';
require __DIR__.'/AppKernel.php';
require __DIR__.'/App.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new \fixtures\AppKernel('test', true);
$application = new Application($kernel);
$application->run();
