#!/usr/bin/env php
<?php

$loader = require __DIR__.'/../../../vendor/autoload.php';
$loader->add('App', __DIR__.'/tmp');
require __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new \fixtures\AppKernel;
$application = new Application($kernel);
$application->run();
